apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-kubernetes
  template:
    metadata:
      labels:
        app: go-kubernetes
    spec:
      containers:
      - name: go-kubernetes-container
        image: sataga/go-kubernetes
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
