settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: go_dev
    path: .
    commands:
      install:
        status: true
        method: go build -o /app/go_dev
      run:
        status: true
        method: /go/bin/dlv
    args:
      - exec
      - /app/go_dev
      - --headless=true
      - --listen=:3000
      - --api-version=2
      - --accept-multiclient
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore:
        paths:
          - .git
          - .realize
          - vendor
